### 메뉴관리

### 1. 메뉴 조회
GET {{common-path}}/api/menus/get-list
Content-Type: application/json


### 2. 렌더 메뉴 조회
GET {{common-path}}/api/menus/get-list/render
Content-Type: application/json



### 3. 메뉴 생성, 수정, 삭제
POST {{common-path}}/api/menus/update
Content-Type: application/json

[
  {
    "menuId": "1",
    "menuNm": "테스트",
    "lnkgUrlAddrCn": "",
    "menuExplnCn": "",
    "menuSortSn": 1,
    "upMenuId": "",
    "insdPrgrmIdntfNm": ""
  }
]



