export enum PageType {
  Menu = 'menu',
  RouteMap = 'routeMap',
  Banner = 'banner',
  OperationInfo = 'operationInfo',
  BatchCycle = 'batch-cycle',
  CarriageInfo = 'carriageInfo',
  ProgrammingInfo = 'programming-info',
  StationInfo = 'station-info',
  CongestionStep = 'CongestionStep',
  EvacuationInfo = 'evacuation-info',
  ZoneInfo = 'zone-info',
  SpecialPeriod = 'special-period',
  Instrumentation = 'instrumentation',
  SaveConditionImage = 'save-condition-image',
  EmergencyManual = 'emergency-manual',
  EmergencyActionManual = 'emergency-action-manual',
  EmergencyFieldPersonnel = 'emergency-field-personnel',
  EmergencyGuideInfo = 'emergency-guide-info',
  EmergencyBroadcastControl = 'emergency-broadcast-control',
}