import type {Metadata} from "next";
import {Toaster} from 'react-hot-toast';
import "./globals.scss";
import "@/shared/styles/media.scss";
import RQProviders from "@/shared/provider/RQProvider";
import localFont from "next/font/local";
import SplashWrapper from "@/shared/components/splashWrapper/SplashWrapper";

const pretendard = localFont({
  src: '../../public/fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
    <body className={`${pretendard.variable} antialiased`}>
    <RQProviders>
      <Toaster
        position="top-center"
        toastOptions={{
          style: {fontSize: '14px', zIndex: 100000},
        }}
      />
      <SplashWrapper>
        {children}
      </SplashWrapper>
    </RQProviders>
    </body>
    </html>
  );
}
