import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import MenuLoader from "@/shared/components/menu/MenuLoader";
import RQProviders from "@/shared/provider/RQProvider";
import localFont from "next/font/local";

const pretendard = localFont({
  src: '../../public/fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  // weight: '100 900',
  variable: '--font-pretendard'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
      <RQProviders>
        <MenuLoader />
        <Toaster
          position="top-center"
          toastOptions={{
            style: { fontSize: '14px', zIndex: 100000 },
          }}
        />
        {children}
      </RQProviders>
      </body>
    </html>
  );
}
