import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import MenuLoader from "@/shared/components/menu/MenuLoader";
import RQProviders from "@/shared/provider/RQProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <RQProviders>
        <MenuLoader />
        <Toaster
          position="top-center"
          toastOptions={{
            style: { fontSize: '14px', zIndex: 100000 },
          }}
        />
        {children}
      </RQProviders>
      </body>
    </html>
  );
}
